export const US_MAJOR_CITIES = [
  // State capitals and major cities by state
  "Birmingham, AL",
  "Montgomery, AL",
  "Anchorage, AK",
  "Juneau, AK",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Little Rock, AR",
  "Los Angeles, CA",
  "San Francisco, CA",
  "San Diego, CA",
  "San Jose, CA",
  "Sacramento, CA",
  "Fresno, CA",
  "Oakland, CA",
  "Denver, CO",
  "Colorado Springs, CO",
  "Hartford, CT",
  "Bridgeport, CT",
  "Dover, DE",
  "Wilmington, DE",
  "Jacksonville, FL",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "Tallahassee, FL",
  "Atlanta, GA",
  "Savannah, GA",
  "Honolulu, HI",
  "Boise, ID",
  "Chicago, IL",
  "Springfield, IL",
  "Indianapolis, IN",
  "Des Moines, IA",
  "Wichita, KS",
  "Topeka, KS",
  "Louisville, KY",
  "Frankfort, KY",
  "New Orleans, LA",
  "Baton Rouge, LA",
  "Portland, ME",
  "Augusta, ME",
  "Baltimore, MD",
  "Annapolis, MD",
  "Boston, MA",
  "Worcester, MA",
  "Detroit, MI",
  "Lansing, MI",
  "Grand Rapids, MI",
  "Minneapolis, MN",
  "Saint Paul, MN",
  "Jackson, MS",
  "Kansas City, MO",
  "Saint Louis, MO",
  "Jefferson City, MO",
  "Billings, MT",
  "Helena, MT",
  "Omaha, NE",
  "Lincoln, NE",
  "Las Vegas, NV",
  "Reno, NV",
  "Carson City, NV",
  "Manchester, NH",
  "Concord, NH",
  "Newark, NJ",
  "Jersey City, NJ",
  "Trenton, NJ",
  "Albuquerque, NM",
  "Santa Fe, NM",
  "New York, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Albany, NY",
  "Charlotte, NC",
  "Raleigh, NC",
  "Fargo, ND",
  "Bismarck, ND",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Portland, OR",
  "Salem, OR",
  "Eugene, OR",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Harrisburg, PA",
  "Providence, RI",
  "Charleston, SC",
  "Columbia, SC",
  "Sioux Falls, SD",
  "Pierre, SD",
  "Nashville, TN",
  "Memphis, TN",
  "Houston, TX",
  "Dallas, TX",
  "Austin, TX",
  "San Antonio, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Salt Lake City, UT",
  "Burlington, VT",
  "Montpelier, VT",
  "Virginia Beach, VA",
  "Richmond, VA",
  "Seattle, WA",
  "Spokane, WA",
  "Olympia, WA",
  "Charleston, WV",
  "Milwaukee, WI",
  "Madison, WI",
  "Cheyenne, WY",
].sort();
