import {
  Tent,
  Users,
  Heart,
  Dumbbell,
  Sparkles,
  Cpu,
  Palette,
  Gamepad2,
  Briefcase,
  GraduationCap,
  DollarSign,
  Shirt,
  Film,
} from "lucide-react";

// Interest categories with tags
export const INTEREST_CATEGORIES = [
  {
    name: "Outdoor",
    icon: Tent,
    color: "bg-green-100 text-green-700 border-green-200",
    tags: [
      "Hiking",
      "Camping",
      "Road Trips",
      "Beach",
      "Mountains",
      "National Parks",
      "Adventure Travel",
      "Backpacking",
    ],
  },
  {
    name: "Social Activities",
    icon: Users,
    color: "bg-blue-100 text-blue-700 border-blue-200",
    tags: [
      "Networking",
      "Meetups",
      "Social Events",
      "Parties",
      "Happy Hour",
      "Clubbing",
      "Bars",
      "Dancing",
    ],
  },
  {
    name: "Hobbies and Passion",
    icon: Heart,
    color: "bg-pink-100 text-pink-700 border-pink-200",
    tags: [
      "Photography",
      "Reading",
      "Writing",
      "Crafts",
      "DIY",
      "Vintage Fashion",
      "Sneakers",
      "Collecting",
    ],
  },
  {
    name: "Sports and Fitness",
    icon: Dumbbell,
    color: "bg-orange-100 text-orange-700 border-orange-200",
    tags: [
      "Gym",
      "Running",
      "Yoga",
      "Swimming",
      "Cycling",
      "Basketball",
      "Soccer",
      "Tennis",
      "Martial Arts",
    ],
  },
  {
    name: "Health and Wellbeing",
    icon: Sparkles,
    color: "bg-purple-100 text-purple-700 border-purple-200",
    tags: [
      "Meditation",
      "Wellness",
      "Spa",
      "Mental Health",
      "Nutrition",
      "Mindfulness",
      "Self-care",
    ],
  },
  {
    name: "Technology",
    icon: Cpu,
    color: "bg-cyan-100 text-cyan-700 border-cyan-200",
    tags: [
      "Coding",
      "AI",
      "Startups",
      "Tech Meetups",
      "Hackathons",
      "Gaming Tech",
      "VR",
      "Crypto",
    ],
  },
  {
    name: "Finance & Economics",
    icon: DollarSign,
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
    tags: [
      "Wall Street",
      "Financial District",
      "Stock Market",
      "Banking",
      "Investment",
      "Economics",
      "Finance Talks",
      "Financial History",
    ],
  },
  {
    name: "Art and Culture",
    icon: Palette,
    color: "bg-indigo-100 text-indigo-700 border-indigo-200",
    tags: [
      "Museums",
      "Art Galleries",
      "Theater",
      "Opera",
      "Ballet",
      "Film",
      "Concerts",
      "Live Music",
    ],
  },
  {
    name: "Fashion & Design",
    icon: Shirt,
    color: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    tags: [
      "Fashion Week",
      "Designer Boutiques",
      "Fashion Shows",
      "Runway Events",
      "Fashion Districts",
      "Textile Arts",
      "Fashion History",
      "Style Workshops",
    ],
  },
  {
    name: "Film & Media",
    icon: Film,
    color: "bg-slate-100 text-slate-700 border-slate-200",
    tags: [
      "Film Festivals",
      "Movie Premieres",
      "Cinema",
      "Film Industry",
      "Screenings",
      "TV Production",
      "Documentary",
      "Independent Films",
    ],
  },
  {
    name: "Games",
    icon: Gamepad2,
    color: "bg-red-100 text-red-700 border-red-200",
    tags: [
      "Video Games",
      "Board Games",
      "E-Sports",
      "Gaming",
      "Tabletop RPG",
      "Card Games",
      "Arcade",
    ],
  },
  {
    name: "Career and Business",
    icon: Briefcase,
    color: "bg-gray-100 text-gray-700 border-gray-200",
    tags: [
      "Networking",
      "Conferences",
      "Workshops",
      "Professional Development",
      "Entrepreneurship",
      "Leadership",
    ],
  },
  {
    name: "Science and Education",
    icon: GraduationCap,
    color: "bg-yellow-100 text-yellow-700 border-yellow-200",
    tags: [
      "Lectures",
      "Workshops",
      "Book Clubs",
      "Learning",
      "Research",
      "STEM",
      "History",
      "Language Exchange",
    ],
  },
];
